version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Generate Report
          command: npm run report
      - store_artifacts:
          path: ~/repo/newman